[display]
rss_url = "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
location = [40.75, -73.99]
timezone = "America/New_York"
locale = "en_US"
units = "imperial"
refresh_interval_sec = 1800  # refresh every 30 minutes